src/main/java/br/ufpa/labes/eas/controller/MotivoMB.java
package br.ufpa.labes.eas.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.PrimeFaces;

import br.ufpa.labes.eas.model.Motivo;
import br.ufpa.labes.eas.model.TipoCongo;
import br.ufpa.labes.eas.service.MotivoService;
import br.ufpa.labes.eas.service.TipoCongoService;
import br.ufpa.labes.eas.util.FacesMessages;

@Named
@ViewScoped
public class MotivoMB implements Serializable {

    private static final long serialVersionUID = -242578804412899747L;

    @Inject
    private MotivoService motivoService;

    @Inject
    private TipoCongoService tipoCongoService;

    @Inject
    private FacesMessages messages;

    private List<Motivo> todosMotivos;

    private Motivo motivoSelecionado;

    private Motivo motivoEdicao = new Motivo();

    private TipoCongo tipoCongoEdicao = new TipoCongo();

    public void salvar() {

        try {
            final Integer peso = this.motivoEdicao.getTipoCongo().getPeso();
            this.motivoEdicao.setPeso(peso);

            this.motivoService.salvar(this.motivoEdicao);
            this.inicializar();

            this.messages.info("Motivo salvo com sucesso!");

            PrimeFaces.current().ajax().update("frm-tabela-motivo:growl-global");
            PrimeFaces.current().ajax().update("frm-tabela-motivo");
        } catch (final Exception e) {
            this.messages.error(e.getMessage());
        }
    }

    public void excluir() {

        try {

            this.motivoService.excluir(this.motivoSelecionado);
            this.messages.info("Motivo excluído com sucesso.");
            this.motivoSelecionado = null;
            this.inicializar();

            PrimeFaces.current().ajax().update("frm-tabela-motivo:growl-global");
            PrimeFaces.current().ajax().update("frm-tabela-motivo");

        } catch (final Exception e) {
            this.messages.error(e.getMessage());
        }

    }

    public void inicializar() {

        this.limpar();
        this.todosMotivos = this.motivoService.buscarTodos();
    }

    public void limpar() {

        this.motivoSelecionado = null;

        this.tipoCongoEdicao = new TipoCongo();
        this.motivoEdicao = new Motivo();
    }

    public Motivo getMotivoSelecionado() {

        return this.motivoSelecionado;
    }

    public void setMotivoSelecionado(final Motivo motivoSelecionado) {

        this.motivoSelecionado = motivoSelecionado;
    }

    public Motivo getMotivoEdicao() {

        return this.motivoEdicao;
    }

    public void setMotivoEdicao(final Motivo motivoEdicao) {

        this.motivoEdicao = motivoEdicao;
    }

    public TipoCongo getTipoCongoEdicao() {

        return this.tipoCongoEdicao;
    }

    public void setTipoCongoEdicao(final TipoCongo tipoCongoEdicao) {

        this.tipoCongoEdicao = tipoCongoEdicao;
    }

    public List<Motivo> getTodosMotivos() {

        return this.todosMotivos;
    }

    public List<TipoCongo> getTiposCongos() {

        return this.tipoCongoService.buscarTodos();
    }

}

src/main/webapp/publico/FuncionarioCongos.xhtml
<ui:composition
	template="/WEB-INF/templates/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo">Quado de Localização</ui:define>

	<ui:define name="corpo">

		<f:metadata>
			<f:viewAction action="#{usuarioMB.inicializar}" />
			<f:viewAction action="#{motivoMB.inicializar}" />
			<f:viewAction action="#{cargoMB.inicializar}" />
			<f:viewAction action="#{localizacaoMB.inicializar}" />
			
			<f:viewParam name="codigo" value="#{usuarioMB.usuarioSelecionado}" converter="conversorGenericoJSF"/>
		</f:metadata>

		<p:panel
			id="panel-titulo"
			header="Sistema Interno Infomática"
			style="margin-bottom:10px; ">

			<h:form id="frm-tabela">

				<p:growl id="growl-global" />

				<p:dataTable
					var="usuario"
					id="tabela-localizacao"
					widgetVar="localizacaoWidget"
					value="#{usuarioMB.todosCongosPeloUsuario}"
					emptyMessage="Nenhum funcionário encontrado."
					style="margin-top: 10px;width:70%;margin-left: 15%">

					<p:ajax
						event="rowSelect"
						update="@this" />
					<p:ajax
						event="rowUnselect"
						update="@this" />

					<f:facet name="header">
						Quadro de Localização
					</f:facet>

					<p:column
						headerText="Nome"
						width="240"
						sortBy="#{usuario.nome}">
						<h:outputText value="#{usuario.nome}" />
					</p:column>

					<p:column
						headerText="Localização"
						width="70"
						sortBy="#{usuario.localizacao.localizacaoPai.nome}">
						<h:outputText value="#{usuario.localizacao.localizacaoPai.nome}" />
					</p:column>

					<p:column
						headerText="Departamento"
						width="80"
						sortBy="#{usuario.localizacao.nome}">

						<h:outputText value="#{usuario.localizacao.nome}" />
					</p:column>
					<p:column
						headerText="Rádio"
						width="40"
						sortBy="#{usuario.radio}">
						<h:outputText value="#{usuario.radio ? 'Sim' : 'Não'}" />
					</p:column>

					<p:column
						headerText="Inconformidades"
						width="105">
						<h:outputText value="#{usuario.quantidadeTotal}" />
					</p:column>

				</p:dataTable>
		</h:form>
		</p:panel>

	</ui:define>


</ui:composition>

src/main/webapp/publico/LocalizacaoFuncionarios.xhtml
<ui:composition
	template="/WEB-INF/templates/LayoutPadrao.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="titulo">Quado de Localização</ui:define>

	<ui:define name="corpo">

		<f:metadata>
			<f:viewAction action="#{usuarioMB.inicializar}" />
			<f:viewAction action="#{motivoMB.inicializar}" />
			<f:viewAction action="#{cargoMB.inicializar}" />
			<f:viewAction action="#{localizacaoMB.inicializar}" />
		</f:metadata>

		<p:panel
			id="panel-titulo"
			header="Sistema Interno Infomática"
			style="margin-bottom:10px; ">

			<h:form id="frm">

				<p:growl id="growl-global" />

				<p:dataTable
					var="usuario"
					id="tabela-localizacao"
					widgetVar="localizacaoWidget"
					value="#{usuarioMB.todosUsuarios}"
					emptyMessage="Nenhum funcionário encontrado."
					selection="#{usuarioMB.usuarioSelecionado}"
					selectionMode="single"
					rowKey="#{usuario.codigo}"
					style="margin-top: 10px;width:70%;margin-left: 15%">

					<p:ajax
						event="rowSelect"
						update="@this" />
					<p:ajax
						event="rowUnselect"
						update="@this" />

					<f:facet name="header">
						Quadro de Localização
					</f:facet>

					<p:column
						headerText="Nome"
						width="240"
						sortBy="#{usuario.nome}">
						<h:outputText value="#{usuario.nome}" />
					</p:column>

					<p:column
						headerText="Localização"
						width="50"
						sortBy="#{usuario.localizacao.localizacaoPai.nome}">
						<h:outputText value="#{usuario.localizacao.localizacaoPai.nome}" />
					</p:column>

					<p:column
						headerText="Departamento"
						width="60"
						sortBy="#{usuario.localizacao.nome}">

						<h:outputText value="#{usuario.localizacao.nome}" />
					</p:column>
					<p:column
						headerText="Rádio"
						width="40"
						sortBy="#{usuario.radio}">
						<h:outputText value="#{usuario.radio ? 'Sim' : 'Não'}" />
					</p:column>

					<p:column
						headerText="Inconformidades"
						width="60">
						<h:outputText value="#{usuario.quantidadeTotal}" />
					</p:column>

					<p:column
						headerText="Ações"
						width="150">
						<h:panelGroup id="acoes">
							<p:commandButton
								id="alterarLocalicacao-button"
								icon="fa fa-map-marker"
								process="@this"
								update=":frm:dialog-localizacao"
								title="Alterar a localização"
								disabled="#{usuarioMB.usuarioSelecionado == null}"
								oncomplete="PF('alterarLocalizacaoDialog').show()"
								style="margin-right: 20px;margin-left: 15%;">
								<p:resetInput target=":frm:dialog-localizacao" />

								<f:setPropertyActionListener
									value="#{usuarioMB.usuarioSelecionado}"
									target="#{usuarioMB.usuarioEdicao}" />
							</p:commandButton>
							<p:commandButton
								id="adicionarCongo-button"
								icon="fa fa-plus-square"
								title="Adicionar Inconformidade"
								process="@this"
								action="#{motivoMB.limpar}"
								update=":frm:dialog-congo"
								disabled="#{usuarioMB.usuarioSelecionado == null}"
								oncomplete="PF('adicionarCongoDialog').show()"
								style="margin-right: 20px;">
								<p:resetInput target=":frm:dialog-congo" />

								<f:setPropertyActionListener
									value="#{usuarioMB.usuarioSelecionado}"
									target="#{usuarioMB.usuarioEdicao}" />
							</p:commandButton>

							<p:commandButton
								icon="fa fa-area-chart"
								title="Visualizar todos os congos"
								process="@this"
								update=":frm:dialog-visualizar"
								action="#{usuarioMB.preparalistaUsuariosPeloCongo}"
								oncomplete="PF('visualizarCongoDialog').show()"
								styleClass="icon-personalizado">
								<p:resetInput target=":frm:dialog-visualizar" />

								<f:setPropertyActionListener
									value="#{usuarioMB.usuarioSelecionado}"
									target="#{usuarioMB.usuarioEdicao}" />

							</p:commandButton>
						</h:panelGroup>
					</p:column>

				</p:dataTable>

				<p:dialog
					header="Alterar Localização"
					id="dialog-localizacao"
					widgetVar="alterarLocalizacaoDialog"
					modal="true"
					draggable="false"
					resizable="false"
					responsive="true">

					<p:messages id="message-localizacao" />

					<p:panelGrid columns="2">

						<p:outputLabel
							value="Nome"
							for="nome" />
						<p:outputLabel
							id="nome"
							value="#{usuarioMB.usuarioEdicao.nome}" />

						<p:outputLabel
							value="Localização"
							for="localizacao" />

						<p:selectOneMenu
							id="localizacao"
							converter="conversorGenericoJSF"
							value="#{usuarioMB.usuarioEdicao.localizacao}">
							<f:selectItems
								var="localizacao"
								value="#{localizacaoMB.todasLocalizacoesFilhas}"
								itemLabel="#{localizacao.nome}"
								itemValue="#{localizacao}" />
						</p:selectOneMenu>

						<p:commandButton
							value="Salvar"
							action="#{usuarioMB.alterarLocalizacao}"
							update="message-localizacao"
							process="message-localizacao"
							oncomplete="if (!args.validationFailed) PF('alterarLocalizacaoDialog').hide()" />

					</p:panelGrid>
				</p:dialog>

				<p:dialog
					header="Adicionar Congo"
					id="dialog-congo"
					widgetVar="adicionarCongoDialog"
					modal="true"
					draggable="false"
					resizable="false"
					responsive="true">

					<p:messages id="message-congo" />

					<p:panelGrid columns="2">

						<p:outputLabel
							value="Nome"
							for="nomeUsuario" />
						<p:outputLabel
							id="nomeUsuario"
							value="#{usuarioMB.usuarioEdicao.nome}" />


						<p:outputLabel
							value="Categoria"
							for="categoria" />

						<p:selectOneMenu
							id="categoria"
							converter="conversorGenericoJSF"
							value="#{usuarioMB.tipoCongoEdicao}">
							<f:selectItem itemLabel="Selecione" />
							<f:selectItems
								var="tipo"
								value="#{motivoMB.tiposCongos}"
								itemLabel="#{tipo.nome}"
								itemValue="#{tipo}" />

							<p:ajax
								listener="#{usuarioMB.buscarPeloCongo}"
								update="select-inconformidade" />
						</p:selectOneMenu>

						<p:outputLabel
							value="Inconformidade"
							for="inconformidade" />

						<h:panelGroup id="select-inconformidade">
							<p:selectOneMenu
								id="inconformidade"
								converter="conversorGenericoJSF"
								value="#{usuarioMB.congoEdicao.motivo}">
								<f:selectItem itemLabel="Selecione" />
								<f:selectItems
									var="motivo"
									value="#{usuarioMB.todosMotivosPeloCongo}"
									itemLabel="#{motivo.motivo}"
									itemValue="#{motivo}" />
							</p:selectOneMenu>

						</h:panelGroup>

						<p:outputLabel />
						<p:commandButton
							value="Apicar inconformidade"
							action="#{usuarioMB.adicionarInconformidade}"
							update="message-congo"
							process="dialog-congo"
							oncomplete="if (!args.validationFailed) PF('adicionarCongoDialog').hide()" />

					</p:panelGrid>
				</p:dialog>

				<p:dialog
					width="80%"
					id="dialog-visualizar"
					widgetVar="visualizarCongoDialog"
					modal="true"
					closeOnEscape="true"
					draggable="false"
					resizable="false"
					responsive="true">

					<p:panelGrid
						columns="2"
						layout="grid">
						<p:outputLabel
							value="Nome: #{usuarioMB.usuarioSelecionado.nome}" />
						<p:outputLabel
							value="Equipe: #{usuarioMB.usuarioSelecionado.cargo.nome}" />
					</p:panelGrid>

					<p:panelGrid columns="2">
						<f:facet name="header">
						Inconformidades
					</f:facet>
						<p:dataTable
							var="congo"
							id="tabela-visualizar"
							widgetVar="visualizarWidget"
							value="#{usuarioMB.todosCongosPeloUsuario}"
							emptyMessage="Nenhuma inconformidade encontrada."
							style="margin-top: 10px;width:70%;margin-left: 15%">

							<p:column
								headerText="Data"
								sortBy="#{congo.data}">
								<p:outputLabel
									id="date"
									value="#{congo.data}">
									<f:convertDateTime pattern="dd/MM/yyyy HH:mm" />
								</p:outputLabel>
							</p:column>
							<p:column
								headerText="Motivo"
								sortBy="#{congo.motivo.motivo}">
								<p:outputLabel
									id="motivoCongo"
									value="#{congo.motivo.motivo}" />
							</p:column>
							<p:column
								headerText="Peso"
								sortBy="#{congo.motivo.peso}">
								<p:outputLabel
									id="pesoCongo"
									value="#{congo.motivo.peso}" />
							</p:column>
							<p:column
								headerText="Tipo"
								sortBy="#{congo.motivo.tipoCongo.nome}">
								<p:outputLabel
									id="tipoCongo"
									value="#{congo.motivo.tipoCongo.nome}" />
							</p:column>

						<f:facet name="footer">
							<p:outputLabel
								id="total"
								style="font-weight: bold;"
								value="Total de Congos: #{usuarioMB.usuarioSelecionado.quantidadeTotal}" />
					</f:facet>
						</p:dataTable>

					</p:panelGrid>
				</p:dialog>

			</h:form>
		</p:panel>

	</ui:define>


</ui:composition>